name: "Setup rez"
description: "Install and bind rez packages."
author: "Joseph Yu (https://github.com/j0yu)"
branding:
  icon: "arrow-down-circle"
  color: "orange"

inputs:
  source:
    description: "GitHub repository to install rez from."
    required: false
    default: 'nerdvegas/rez'

  ref:
    description: "Git tag/branch/commit to use."
    required: false
    default: 'master'

  makePackagesPaths:
    description: Create all default "rez config packages_path".
    required: false
    default: true

  binds:
    description: >
      Comma separated packages to rez bind, e.g. "os, python".
      See "rez bind --list". Will force the creation of
      "rez config local_packages_path"
    required: false
    default: os, python

runs:
  using: 'node12'
  main: 'index.js'
