name: CI
on: [push]

jobs:
  test-linux-containers:
    name: ${{ matrix.os }} Py${{ matrix.python }}
    runs-on: ubuntu-latest
    container: ${{ matrix.os }}
    strategy:
      matrix:
        os:
        - "centos:8"
        python:
        - 2.7
        - 3.7
      fail-fast: false  # true

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "${{ matrix.python }}"

      - run: rpm -qi glibc
      - name: echo "::set-env name=LD_LIBRARY_PATH::$(readlink -m $(command -v python${{ matrix.python }})/../../lib)"
      - run: python${{ matrix.python }} -c "import sys; print(sys.version_info)"
      - uses: ./

      - run: rez --version
      - run: rez config local_packages_path
      - run: rez config release_packages_path
      - run: rez config packages_path
      - run: rez view os
      - run: rez view python
